[tool.pygbag]
assets = ["resources/assets"]

[build]
assets = [
    "resources/sewer.tsx",
    "resources/sewermap.tmx",
    "resources/MOUSE.png",
    "resources/idle.png",
    "resources/title.tmx"
]
entrypoint = "main.py"
